length.o: length.c
	gcc -c -g -I../include length.c -o length.o
pressure.o: pressure.c
	gcc -c -g -I../include pressure.c -o pressure.o
temp.o: temp.c
	gcc -c -g -I../include temp.c -o temp.o
volume.o: volume.c
	gcc -c -g -I../include volume.c -o volume.o
weight.o: weight.c
	gcc -c -g -I../include weight.c -o weight.o


